/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import { Contract, ContractFactory, Overrides } from "@ethersproject/contracts";

import type { ChainLinkFeedsMap } from "../ChainLinkFeedsMap";

export class ChainLinkFeedsMap__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(overrides?: Overrides): Promise<ChainLinkFeedsMap> {
    return super.deploy(overrides || {}) as Promise<ChainLinkFeedsMap>;
  }
  getDeployTransaction(overrides?: Overrides): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): ChainLinkFeedsMap {
    return super.attach(address) as ChainLinkFeedsMap;
  }
  connect(signer: Signer): ChainLinkFeedsMap__factory {
    return super.connect(signer) as ChainLinkFeedsMap__factory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ChainLinkFeedsMap {
    return new Contract(address, _abi, signerOrProvider) as ChainLinkFeedsMap;
  }
}

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
];

const _bytecode =
  "0x6080604052348015600f57600080fd5b50603f80601d6000396000f3fe6080604052600080fdfea26469706673582212208f423fed72fdd351597b6990f3ac8126cf4e5cb0bce3b92077cb8a53c16508f164736f6c63430008000033";
