/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IChainLinkFeedsMapETHMainnet } from "../IChainLinkFeedsMapETHMainnet";

export class IChainLinkFeedsMapETHMainnet__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IChainLinkFeedsMapETHMainnet {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IChainLinkFeedsMapETHMainnet;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "isChainLinkFeed",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];
