/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IChainLinkFeedsMapMumbai } from "../IChainLinkFeedsMapMumbai";

export class IChainLinkFeedsMapMumbai__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IChainLinkFeedsMapMumbai {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IChainLinkFeedsMapMumbai;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "feed",
        type: "address",
      },
    ],
    name: "isChainLinkFeed",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];
